version: '3'
services:
  images-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo

  # redis: 
  #   image: redis:alpine
  #   command: ["redis-server", "--appendonly", "yes"]
  #   hostname: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: always
  redis:
    image: redis
    ports:
        - "6379"
  mongo:
    image: mongo:latest
networks:
  redis-net:
     driver: bridge
volumes:
  redis-data:
    